---
title: "capstone_variablecreation"
author: "Laura Olson"
date: "May 20, 2017"
output: html_document
---

```{r}
#libraries being used in this file
library(dplyr)


```


#Segment patients with hep c at first encounter vs. after

#Create table patients

```{r}
########Find Hep C patients from icd diagnosis codes

##Match icd 9 codes per Dr Davis's email
hep_c_icd_dx <- subset(diagnosis_icd, 
                        icd_dx == "V02.62" | #Carrier or suspected carrier of Hep C (icd9)
                        icd_dx == "Z22.52" | #Carrier or suspected carrier of Hep C (icd10)
                        icd_dx == "V12.09" | #Hepatitis C, history of (icd9)
                        #icd_dx == "070.41" | #Acute hepatitis C with hepatic coma (icd9)
                        #icd_dx == "070.44" | #Chronic hepatitis C with hepatic coma (icd9)
                        #icd_dx == "070.51" | #Acute hepatitis C without mention of hepatic coma (icd9)
                        icd_dx == "070.54" | #Chronic hepatitis C without mention of hepatic coma; reat that it can be used as hep c in remission (icd9)
                        #icd_dx == "070.7" | #Unspecified viral hepatitis C (icd9)
                        icd_dx == "070.70" | #Unspecified viral hepatitis C without hepatic coma (icd9)
                        icd_dx == "070.71" | #Unspecified viral hepatitis C with hepatic coma (icd9)
                        icd_dx == "B19.20" | #Unspecified viral hepatitis C without hepatic coma (icd10)
                        icd_dx == "B1920" | #Unspecified viral hepatitis C without hepatic coma (icd10)
                        icd_dx == "B18.2" | #Chronic viral hep C (icd10)
                        #icd_dx == "B1710" | #Acute hepatitis C without hepatic coma (icd10)
                        icd_dx == "B19.21" | #Unspecified viral hepatitis C with hepatic coma (icd10)
                        icd_dx == "B1921"  #Unspecified viral hepatitis C with hepatic coma (icd10)
)

#Codes below were not included - These are icd 10 codes - there doesn't seem to be specific Hep C codes during pregnancy for icd 9
#"O98411" (icd10) - Viral hepatitis complicating pregnancy, first trimester
#"O98412" (icd10) - Viral hepatitis complicating pregnancy, second trimester
#"O9842" (icd10) - "VIRAL HEPATITIS COMPLICATING CHILDBIRTH"  
#"O98413" (icd10) - "VIRAL HEPATITIS COMP PREGNANCY THIRD TRIMESTER" 

dim(hep_c_icd_dx)#26540
#table(hep_c_icd_dx$icd_dx)
#table(hep_c_icd_dx$icd_diagnosis)


length(unique(hep_c_icd_dx$PATIENT_ID)) #3768 unique patient id's #3707

#####Find first hep c diagnosis dates#######

#Create an object with id numbers of unique patients with a Hep C icd code and the date of that first diagnosis date
#####

#find earilest hep C icd code using aggregate 
hep_c_patients_ids_first_hep_c_encounter_date <- aggregate(enc_dt_ds~PATIENT_ID,  data = hep_c_icd_dx, min) 

#rename encounter date column
names(hep_c_patients_ids_first_hep_c_encounter_date)[names(hep_c_patients_ids_first_hep_c_encounter_date) == "enc_dt_ds"] <- "First_Date_with_Hep_C_ICD_code"

#str(hep_c_patients_ids_first_hep_c_encounter_date)
#dim(hep_c_patients_ids_first_hep_c_encounter_date)
#length(unique(hep_c_patients_ids_first_hep_c_encounter_date$PATIENT_ID))

```




```{r}

##Finding first encounter date for Hep C patients
#Filter encounter table on Hep C patients only
hep_c_patient_encounters <- encounters[encounters$PATIENT_ID %in% hep_c_patients_ids_first_hep_c_encounter_date$PATIENT_ID,]
#names(hep_c_patient_encounters)

#reduce dataset to date and id field only
hep_c_patient_encounters_dates <- hep_c_patient_encounters[c("PATIENT_ID", "ENCOUNTER_ID", "PAT_ENC_CSN_ID_DID", "Enc_DT_DS", "Appt_DTTM_DS", "Appt_Checkin_DTTM", "Appt_Cancel_DTTM_DS", "ED_Arrival_DTTM_DS", "Hsp_Adm_DTTM_DS", "Hsp_Disch_DTTM_DS")]
#dim(hep_c_patient_encounters_dates)


#find min encounter date for hep C patients; change column name 
hep_c_patients_first_encounter_date <- aggregate(Enc_DT_DS~PATIENT_ID,  data = hep_c_patient_encounters_dates, min)
names(hep_c_patients_first_encounter_date)[names(hep_c_patients_first_encounter_date) == "Enc_DT_DS"] <- "First_Encounter_Date"
str(hep_c_patients_ids_first_hep_c_encounter_date)

#merge encounter dates with first hep c diangosis date
hep_c_patients_first_encounter_date_and_first_hep_c_icd_code <- merge(hep_c_patients_first_encounter_date, hep_c_patients_ids_first_hep_c_encounter_date, by ="PATIENT_ID")
str(hep_c_patients_first_encounter_date_and_first_hep_c_icd_code)

#Evaluate whether first enounter date is greater, less or equal to first encounter date - patients diagnosed within our periods of interest are "TRUE"
hep_c_patients_first_encounter_date_and_first_hep_c_icd_code$EncountervsICD <- ifelse(hep_c_patients_first_encounter_date_and_first_hep_c_icd_code$First_Encounter_Date < hep_c_patients_first_encounter_date_and_first_hep_c_icd_code$First_Date_with_Hep_C_ICD_code,  "TRUE", "FALSE")

#nrow(subset(hep_c_patients_first_encounter_date_and_first_hep_c_icd_code, EncountervsICD == 'TRUE'))
#nrow(subset(hep_c_patients_first_encounter_date_and_first_hep_c_icd_code, EncountervsICD == 'FALSE'))

```



```{r}


#include patients whose first encounter date was <= to first Hep C icd code - patients diagnosed during our time horizon
patients_include <- subset(hep_c_patients_first_encounter_date_and_first_hep_c_icd_code, EncountervsICD == "TRUE")

#create table with all unique patient ID's from all tables except meds_inpt and meds_outpt
unique_pt_id_all_tbls<-as.data.frame(unique(c(cpt$PATIENT_ID,demo$PATIENT_ID,diagnosis_icd$PATIENT_ID,education$PATIENT_ID,encounters$PATIENT_ID,labs$PATIENT_ID,med_rec_adm$PATIENT_ID,med_rec_dc$PATIENT_ID,procedure_icd$PATIENT_ID,social_hx$PATIENT_ID)))
names(unique_pt_id_all_tbls)[1]<-paste("PATIENT_ID")

#exclude patients who have hep c but didn't get it during our time horizon
patients_exclude <- subset(hep_c_patients_first_encounter_date_and_first_hep_c_icd_code, EncountervsICD == "FALSE")

#master list of patients in scope for the analysis
patients <- left_join(unique_pt_id_all_tbls,patients_include)
old_rows<-nrow(patients)
patients<-anti_join(patients,patients_exclude, by = "PATIENT_ID")
new_rows<-nrow(patients)
deleted_rows<-old_rows-new_rows; deleted_rows

#Add column to identify as hep c = 1 and non hep c = 1
patients$HCV_STATUS <- ifelse(is.na(patients$First_Date_with_Hep_C_ICD_code),0,1)
patients<-patients[order(patients$PATIENT_ID),]


dim(patients)
str(patients)


#double check - should be 2485
nrow(subset(patients, HCV_STATUS ==1))

#for patients who are not diagnosed with Hep_C make the First_Date_with_Hep_C_ICD_code 9999-12-31
patients$enddate<-as.Date.character("9999-12-31","%Y-%m-%d")
patients$first_date<-as.Date.numeric(ifelse(is.na(patients$First_Date_with_Hep_C_ICD_code),patients$enddate,patients$First_Date_with_Hep_C_ICD_code),origin = "1970-01-01")
patients$First_Date_with_Hep_C_ICD_code<-patients$first_date

#reduce to only patient ID and HCV status, first diagnosis date
patients <- patients[,c(1, 3, 5)]

```

```{r}
#######Demo Varialbes#####

#merge patient id's with demo table

dim(demo)
dim(patients)
pts_demo <- left_join(patients, demo) #add demographics
dim(pts_demo)

str(pts_demo)


pts_demo <- pts_demo[,c( "PATIENT_ID", "HCV_STATUS", "DOB_DS", "Gender", "Race", "Ethnicity", "language", "Marital_Status",      "DOD_DS")] #reducing down the columns
names(pts_demo)[c(3:9)] <- c("DOB","GENDER", "RACE", "ETHNICITY", "LANGUAGE", "MARITAL_STATUS", "DOD") #rename columns

library(eeptools)
## DOB ##
pts_demo$age_T0 <- age_calc(dob = DOB, enddate = , units = "years")

## reduce Language levels to 2

levels(pts_demo$language)

levels(pts_demo$LANGUAGE) <- c("Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English",
"Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English",
"Non-English", "Non-English", "Non-English", "Non-English", "Non-English", "Non-English") #reducing language to 2 factors

#reduce Marital Status levels to 4

levels(pts_demo$MARITAL_STATUS) <- c("Married_Committed", "Married_Committed", "Unknown", "Divorced_Separated", 
                                     "Divorced_Separated", "Unknown", "Unknown", "Unknown", 
                                     "Unknown", "Divorced_Separated", "Divorced_Separated", "Unknown", 
                                     "Unknown", "Married_Committed", "Unknown", "Unknown", 
                                     "Married_Committed", "Unknown", "Unknown", "Unknown",
                                     "Unknown", "Unknown", "Single", "Unknown", 
                                     "Unknown", "Unknown", "Unknown", "Unknown",
                                     "Unknown", "Unknown", "Unknown", "Unknown",
                                    "Widowed", "Unknown", "Unknown", "Unknown", 
                                    "Unknown", "Unknown")
```

```{r}

#####  Social History Variables ####

#merge patient id's with social history table

dim(social_hx)
dim(patients)
pts_social <- left_join(patients, social_hx) #add demographics
dim(pts_social)

str(pts_social)
pts_social<-pts_social[order(pts_social$PATIENT_ID),]

#remove observations after First_Date_with_Hep_C_ICD_code; also removes observations where the Enc_DT_DS is blank because we are not able ot determine when the social survey was taken.
pts_social$BeforeorAfter <-ifelse(pts_social$First_Date_with_Hep_C_ICD_code=="9999-12-31", 1,
                                        ifelse(pts_social$First_Date_with_Hep_C_ICD_code < pts_social$Enc_DT_DS, 0, 1))

nrow(subset(pts_social, BeforeorAfter == 0))
nrow(subset(pts_social, BeforeorAfter == 1))

pts_social <- subset(pts_social, BeforeorAfter == 1)
#old_rows<-nrow(pts_social[1])
#remove duplicated rows - no duplicates present
#pts_social <- pts_social[!duplicated(pts_social),]
#new_rows<-nrow(pts_social)
#rows_deleted<-old_rows-new_rows; rows_deleted


##### Tobacco ####

###Convert all of these to Ever/Never/No Data = 2/1/0
#TOBACCO_USER
#SMOKING_TOB_USE
#SMOKELESS_TOB_USE
#CIGARETTES_YN
#PIPES_YN
#CIGARS_YN
#SNUFF_YN
#CHEW_YN

#then check if any of then have ever been answered with "2" before and mark the TOBACCO_USER_DER variable "Ever" if they have


#Recoding the TOBACCO_USER status variable -
#NA = 0
#0 = "Not Asked"
#1 = "Never"
#1 = "Passive"
#2 = "Quit"
#2 = "Yes"
pts_social$TOBACCO_USER_FCR<-pts_social$TOBACCO_USER
levels(pts_social$TOBACCO_USER_FCR) <- c("1", "0", "1", "2", "2")
#nrow(subset(pts_social,is.na(TOBACCO_USER_DER)=="TRUE"))
pts_social$TOBACCO_USER_FCR[is.na(pts_social$TOBACCO_USER_FCR)] <- "0"
#nrow(subset(pts_social,is.na(TOBACCO_USER_DER)=="TRUE"))
table(pts_social$TOBACCO_USER_FCR,pts_social$TOBACCO_USER)
pts_social$TOBACCO_USER_FCR <- as.numeric(as.character(pts_social$TOBACCO_USER_FCR))

#Recoding the SMOKING_TOB_USE status variable 

#2 - Current Every Day Smoker               
#2 - Current Some Day Smoker 
#2 - Former Smoker
#2 - Heavy Tobacco Smoker
#2 - Light Tobacco Smoker
#0 - Never Assessed
#1 - Never Smoker 
#1 - Passive Smoke Exposure - Never Smoker
#2 - Smoker, Current Status Unknown
#0 - Unknown If Ever Smoked


pts_social$SMOKING_TOB_USE_FCR<-pts_social$SMOKING_TOB_USE
levels(pts_social$SMOKING_TOB_USE_FCR) <- c("2", "2", "2", "2", "2", "0","1","1","0","0")
#nrow(subset(pts_social,is.na(TOBACCO_USER_DER)=="TRUE"))
pts_social$SMOKING_TOB_USE_FCR[is.na(pts_social$SMOKING_TOB_USE_FCR)] <- "0"
#nrow(subset(pts_social,is.na(TOBACCO_USER_DER)=="TRUE"))
table(pts_social$SMOKING_TOB_USE_FCR)
pts_social$SMOKING_TOB_USE_FCR <- as.numeric(as.character(pts_social$SMOKING_TOB_USE_FCR))


#Recoding the SMOKELESS_TOB_USE status variable 
#2 - Current User
#2 - Former User
#1 - Never Used
#0 - Unknown
#Yes - 2

pts_social$SMOKELESS_TOB_USE_FCR<-pts_social$SMOKELESS_TOB_USE
levels(pts_social$SMOKELESS_TOB_USE_FCR) <- c("2", "2", "1", "0","2")
#nrow(subset(pts_social,is.na(TOBACCO_USER_DER)=="TRUE"))
pts_social$SMOKELESS_TOB_USE_FCR[is.na(pts_social$SMOKELESS_TOB_USE_FCR)] <- "0"
#nrow(subset(pts_social,is.na(TOBACCO_USER_DER)=="TRUE"))
table(pts_social$SMOKELESS_TOB_USE_FCR)
pts_social$SMOKELESS_TOB_USE_FCR <- as.numeric(as.character(pts_social$SMOKELESS_TOB_USE_FCR))


#Recoding the CIGARETTES_YN status variable 
#2 - Y
#1 - N
#0 - Unknown

pts_social$CIGARETTES_YN_FCR<-pts_social$CIGARETTES_YN
levels(pts_social$CIGARETTES_YN_FCR) <- c("1", "2","0")
#nrow(subset(pts_social,is.na(TOBACCO_USER_DER)=="TRUE"))
pts_social$CIGARETTES_YN_FCR[is.na(pts_social$CIGARETTES_YN_FCR)] <- "0"
#nrow(subset(pts_social,is.na(TOBACCO_USER_DER)=="TRUE"))
table(pts_social$CIGARETTES_YN_FCR)
pts_social$CIGARETTES_YN_FCR <- as.numeric(as.character(pts_social$CIGARETTES_YN_FCR))


#Recoding the PIPES_YN status variable 
#2 - Y
#1 - N
#0 - Unknown

pts_social$PIPES_YN_FCR<-pts_social$PIPES_YN
levels(pts_social$PIPES_YN_FCR) <- c("1", "2","0")
#nrow(subset(pts_social,is.na(TOBACCO_USER_DER)=="TRUE"))
pts_social$PIPES_YN_FCR[is.na(pts_social$PIPES_YN_FCR)] <- "0"
#nrow(subset(pts_social,is.na(TOBACCO_USER_DER)=="TRUE"))
table(pts_social$PIPES_YN_FCR)
pts_social$PIPES_YN_FCR <- as.numeric(as.character(pts_social$PIPES_YN_FCR))


#Recoding the CIGARS_YN status variable 
#2 - Y
#1 - N
#0 - Unknown

pts_social$CIGARS_YN_FCR<-pts_social$CIGARS_YN
levels(pts_social$CIGARS_YN_FCR) <- c("1", "2","0")
#nrow(subset(pts_social,is.na(TOBACCO_USER_DER)=="TRUE"))
pts_social$CIGARS_YN_FCR[is.na(pts_social$CIGARS_YN_FCR)] <- "0"
#nrow(subset(pts_social,is.na(TOBACCO_USER_DER)=="TRUE"))
table(pts_social$CIGARS_YN_FCR)
pts_social$CIGARS_YN_FCR <- as.numeric(as.character(pts_social$CIGARS_YN_FCR))


#Recoding the SNUFF_YN status variable 
#2 - Y
#1 - N
#0 - Unknown

pts_social$SNUFF_YN_FCR<-pts_social$SNUFF_YN
levels(pts_social$SNUFF_YN_FCR) <- c("1", "2","0")
#nrow(subset(pts_social,is.na(TOBACCO_USER_DER)=="TRUE"))
pts_social$SNUFF_YN_FCR[is.na(pts_social$SNUFF_YN_FCR)] <- "0"
#nrow(subset(pts_social,is.na(TOBACCO_USER_DER)=="TRUE"))
table(pts_social$SNUFF_YN_FCR)
pts_social$SNUFF_YN_FCR <- as.numeric(as.character(pts_social$SNUFF_YN_FCR))


#Recoding the CHEW_YN status variable 
#2 - Y
#1 - N
#0 - Unknown

pts_social$CHEW_YN_FCR<-pts_social$CHEW_YN
levels(pts_social$CHEW_YN_FCR) <- c("1", "2","0")
#nrow(subset(pts_social,is.na(TOBACCO_USER_DER)=="TRUE"))
pts_social$CHEW_YN_FCR[is.na(pts_social$CHEW_YN_FCR)] <- "0"
#nrow(subset(pts_social,is.na(TOBACCO_USER_DER)=="TRUE"))
table(pts_social$CHEW_YN_FCR)
pts_social$CHEW_YN_FCR <- as.numeric(as.character(pts_social$CHEW_YN_FCR))


### create extra variable that takes the max of the other tobacco-related variaables. If the person has ever marked Y on any of them, consider the "smoker"
#TOBACCO_USER
#SMOKING_TOB_USE
#SMOKELESS_TOB_USE
#CIGARETTES_YN
#PIPES_YN
#CIGARS_YN
#SNUFF_YN
#CHEW_YN

pts_social$TOBACCO_USER_STATUS_DER_ENC<-as.numeric("0")

i <-1
cols<-ncol(pts_social)
rows<-nrow(pts_social)
initial_time<-Sys.time()
while (i<=rows){
  ifelse(pts_social[i,(cols-8)]==0 & pts_social[i,(cols-7)]==0 & pts_social[i,(cols-6)]==0 & pts_social[i,(cols-5)]==0& pts_social[i,(cols-4)]==0& pts_social[i,(cols-3)] ==0 & pts_social[i,(cols-2)]==0 & pts_social[i,(cols-1)]==0, 0,  pts_social[i,cols]<- max(pts_social[i,(cols-8):(cols-1)]))
  i=i+1
  print(i/rows)
  final_time<-Sys.time()
  }
final_time-initial_time          

#pts_social[60:150,66:74]



#find max status of tobacco_user
#change formatting of object to factor
pts_max_status <- aggregate(TOBACCO_USER_STATUS_DER_ENC~PATIENT_ID,  data = pts_social, max)
colnames(pts_max_status) <- c("PATIENT_ID", "TOBACCO_USER_STATUS_DER")
pts_max_status$TOBACCO_USER_STATUS_DER<-as.factor(pts_max_status$TOBACCO_USER_STATUS_DER)
levels(pts_max_status$TOBACCO_USER_STATUS_DER) <- c("Unknown", "Never", "Ever")
#head(pts_max_status)
dim(pts_max_status)
str(pts_max_status)
table(pts_max_status$TOBACCO_USER_STATUS_DER)


#Add the variable to the patients table
patients<-left_join(patients,pts_max_status, by = "PATIENT_ID")
patients$TOBACCO_USER_STATUS_DER[is.na(patients$TOBACCO_USER_STATUS_DER)] <- "Unknown"


### Intentsity of tobacco use
pts_max_packs<-aggregate(TOBACCO_PAK_PER_DY~PATIENT_ID, data = pts_social,max)
colnames(pts_max_packs) <- c("PATIENT_ID", "TOBACCO_PAK_PER_DAY")
patients<-left_join(patients,pts_max_packs, by = "PATIENT_ID")
patients$TOBACCO_PAK_PER_DAY[is.na(patients$TOBACCO_PAK_PER_DAY)] <- 0


pts_social<-pts_social[order(-pts_social$TOBACCO_USER_STATUS_DER_ENC,pts_social$PATIENT_ID),]
#validate<-pts_social[,c(1:3,17,18,20,21,74)]


# number of years smoked
pts_max_years<-aggregate(TOBACCO_USED_YEARS~PATIENT_ID, data = pts_social,max)
colnames(pts_max_years) <- c("PATIENT_ID", "TOBACCO_USED_YEARS")
patients<-left_join(patients,pts_max_years, by = "PATIENT_ID")
patients$TOBACCO_USED_YEARS[is.na(patients$TOBACCO_USED_YEARS)] <- 0
patients<-patients[,c(-6,-7)]



##### Alcohol ####
#alcohol related fields: 
#ALCOHOL_USE_C
#ALCOHOL_USE
#HX_DRINK_TYPES_C
#HX_DRINK_TYPES - not using -using alcohol use instead
#ALCOHOL_DRINKS_WK - data quality poor - field mostly blank
#ALCOHOL_OZ_PER_WK
#ALCOHOL_COMMENT

#Recoding the ALCOHOL_USE status variable -
#1 - No
#0 - Not Asked
#2 - Yes

pts_social$ALCOHOL_USE_FCR<-pts_social$ALCOHOL_USE
levels(pts_social$ALCOHOL_USE_FCR) <- c("1", "1","0", "2")
#nrow(subset(pts_social,is.na(ALCOHOL_USE_FCR)=="TRUE"))
pts_social$ALCOHOL_USE_FCR[is.na(pts_social$ALCOHOL_USE_FCR)] <- "0"
#nrow(subset(pts_social,is.na(ALCOHOL_USE_FCR)=="TRUE"))
table(pts_social$ALCOHOL_USE_FCR)
pts_social$ALCOHOL_USE_FCR <- as.numeric(as.character(pts_social$ALCOHOL_USE_FCR))

#alcohol usage
pts_max_alc_use<-aggregate(ALCOHOL_USE_FCR~PATIENT_ID, data = pts_social,max)
colnames(pts_max_alc_use) <- c("PATIENT_ID", "ALCOHOL_USE_FCR")
patients<-left_join(patients,pts_max_alc_use, by = "PATIENT_ID")
patients$ALCOHOL_USE_FCR[is.na(patients$ALCOHOL_USE_FCR)] <- 0


## Alcohol intensiy - ALCOHOL_OZ_PER_WK
pts_social$ALCOHOL_OZ_PER_WK_FCR<-pts_social$ALCOHOL_OZ_PER_WK
pts_social$ALCOHOL_OZ_PER_WK_FCR[is.na(pts_social$ALCOHOL_OZ_PER_WK_FCR)] <- 0
pts_max_alc_oz<-aggregate(ALCOHOL_OZ_PER_WK_FCR~PATIENT_ID, data = pts_social,max)
colnames(pts_max_alc_oz) <- c("PATIENT_ID", "ALCOHOL_OZ_PER_WK_FCR")
patients<-left_join(patients,pts_max_alc_oz, by = "PATIENT_ID")
patients$ALCOHOL_OZ_PER_WK_FCR[is.na(patients$ALCOHOL_OZ_PER_WK_FCR)] <- 0



#### Sexual behavior ########

#Recoding the SEXUALLY_ACTIVE status variable -
#1 - No
#0 - Not Asked
#2 - Not Currently
#2 - Yes

pts_social$SEXUALLY_ACTIVE_FCR<-pts_social$SEXUALLY_ACTIVE
levels(pts_social$SEXUALLY_ACTIVE_FCR) <- c("1", "1", "0", "2","2")
#nrow(subset(pts_social,is.na(SEXUALLY_ACTIVE_FCR)=="TRUE"))
pts_social$SEXUALLY_ACTIVE_FCR[is.na(pts_social$SEXUALLY_ACTIVE_FCR)] <- "0"
#nrow(subset(pts_social,is.na(SEXUALLY_ACTIVE_FCR)=="TRUE"))
table(pts_social$SEXUALLY_ACTIVE_FCR)
pts_social$SEXUALLY_ACTIVE_FCR <- as.numeric(as.character(pts_social$SEXUALLY_ACTIVE_FCR))

#aggregate sexual activity to patient level
pts_max_sex_active<-aggregate(SEXUALLY_ACTIVE_FCR~PATIENT_ID, data = pts_social,max)
colnames(pts_max_sex_active) <- c("PATIENT_ID", "SEXUALLY_ACTIVE_FCR")
patients<-left_join(patients,pts_max_sex_active, by = "PATIENT_ID")
patients$SEXUALLY_ACTIVE_FCR[is.na(patients$SEXUALLY_ACTIVE_FCR)] <- 0

#Recoding the SEX_ENC_TYPE - type of sexual encounter. If the patient has ever had homosexual activity. 
#bring in the demographics table
pts_social<-left_join(pts_social,demo, by = "PATIENT_ID")

#Replace "NA" with U = unknown gender for the patient themselves
nrow(subset(pts_social,is.na(Gender)=="TRUE"))
pts_social$Gender[is.na(pts_social$Gender)] <- "U"
nrow(subset(pts_social,is.na(Gender)=="TRUE"))

#Clean data for the patients partner - Female partner
levels(pts_social$FEMALE_PARTNER_YN) <- c("N", "Y", "U")
nrow(subset(pts_social,is.na(FEMALE_PARTNER_YN)=="TRUE"))
pts_social$FEMALE_PARTNER_YN[is.na(pts_social$FEMALE_PARTNER_YN)] <- "U"
nrow(subset(pts_social,is.na(FEMALE_PARTNER_YN)=="TRUE"))

#Clean data for the patients partner - Male partner
levels(pts_social$MALE_PARTNER_YN) <- c("N", "Y", "U")
nrow(subset(pts_social,is.na(MALE_PARTNER_YN)=="TRUE"))
pts_social$MALE_PARTNER_YN[is.na(pts_social$MALE_PARTNER_YN)] <- "U"
nrow(subset(pts_social,is.na(MALE_PARTNER_YN)=="TRUE"))

#claculate if the the encounter was homosexual, heterosexual or Unknown
pts_social$Sex_Partner_Gender<-ifelse(pts_social$FEMALE_PARTNER_YN=="Y",ifelse(pts_social$MALE_PARTNER_YN=="Y","Mix","F"),ifelse(pts_social$MALE_PARTNER_YN=="Y","M","U"))
pts_social$sex_enc_type<-ifelse(pts_social$Gender=="U" | pts_social$Sex_Partner_Gender=="U","U",ifelse(pts_social$Sex_Partner_Gender=="Mix","HO",ifelse(pts_social$Gender==pts_social$Sex_Partner_Gender,"HO","HE")))
pts_social[100:200,c(1,75,40,41,86,87)]

#aggregate and bring into patients table
#if any homosexual axtivity has been recorded in the past, this variable is flagged HO.
pts_max_sex_enc_type<-aggregate(sex_enc_type~PATIENT_ID, data = pts_social,max)
colnames(pts_max_sex_enc_type) <- c("PATIENT_ID", "SEX_ENC_TYPE")
patients<-left_join(patients,pts_max_sex_enc_type, by = "PATIENT_ID")
patients$SEX_ENC_TYPE[is.na(patients$SEX_ENC_TYPE)] <- "U"

#### Condom use
# y = 2
# N = 1
#n/a = 0

pts_social$CONDOM_YN_FCR<-pts_social$CONDOM_YN
levels(pts_social$CONDOM_YN_FCR) <- c("1", "2")
nrow(subset(pts_social,is.na(CONDOM_YN_FCR)=="TRUE"))
pts_social$CONDOM_YN_FCR <- as.numeric(as.character(pts_social$CONDOM_YN_FCR))
pts_social$CONDOM_YN_FCR[is.na(pts_social$CONDOM_YN_FCR)] <- "0"
nrow(subset(pts_social,is.na(CONDOM_YN_FCR)=="TRUE"))
pts_social$CONDOM_YN_FCR <- as.numeric(as.character(pts_social$CONDOM_YN_FCR))
table(pts_social$CONDOM_YN_FCR)


#aggregate sexual activity to patient level
pts_max_condom_use<-aggregate(CONDOM_YN_FCR~PATIENT_ID, data = pts_social,max)
colnames(pts_max_sex_active) <- c("PATIENT_ID", "CONDOM_YN_FCR")
patients<-left_join(patients,pts_max_sex_active, by = "PATIENT_ID")
patients$CONDOM_YN_FCR[is.na(patients$CONDOM_YN_FCR)] <- 0


##### Occupation#####
#the occupation field is mostly blank - build 2 factors: NA and everything else
pts_social$OCCUPATION_FCR<-pts_social$OCCUPATION

#pts_social$OCCUPATION_FCR[is.na(pts_social$OCCUPATION_FCR)] <- "0"

occupations<-data.frame(table(pts_social$OCCUPATION))

```


```{r}
####  CINDY'S CODE #######
#-----------------------------------



######ICD Diagnosis Codes Table#########

###import value sets
HEDIS_value_sets <- read_delim("Z:/Value Sets/Value_Sets.csv", ",", escape_double = FALSE, trim_ws = TRUE)

HEDIS_value_set <- HEDIS_value_set[1:135657,] #dropping empty rows at end
tail(HEDIS_value_set)
str(HEDIS_value_set)

#reduce value sets to releveant sets and remove duplicate icd codes
hep_c_project_HEDIS_value_sets <- subset(value_sets, Value_Set_Name == "AOD Dependence" |
                                Value_Set_Name == "AOD Procedures" |
                                Value_Set_Name == "AOD Rehab and Detox" |
                                Value_Set_Name == "Chemical Dependency" |
                                Value_Set_Name == "Chlamydia Tests" |
                                Value_Set_Name == "Detoxification" |
                                Value_Set_Name == "Hepatitis A" |
                                Value_Set_Name == "Hepatitis B" |
                                Value_Set_Name == "HIV" |
                                Value_Set_Name == "IV Drug Abuse" |
                                Value_Set_Name == "Sexual Activity")
str(hep_c_project_HEDIS_value_sets) #2015 obserations

hep_c_project_HEDIS_value_sets$Code <- gsub("\\..*", "", hep_c_project_HEDIS_value_sets$Code) #drop the decimal point and any numbers after
hep_c_project_HEDIS_value_sets$Code <- str_pad(hep_c_project_HEDIS_value_sets$Code, 4, pad = "0") #pad so all codes are 4 characters long
hep_c_project_HEDIS_value_sets <- hep_c_project_HEDIS_value_sets[!duplicated(hep_c_project_HEDIS_value_sets$Code),] #remove duplicates icd; some icd codes appear in more than one category #1454 unique icd codes/rows
hep_c_project_HEDIS_value_sets <- subset(hep_c_project_HEDIS_value_sets, Code_System == "ICD9CM" | Code_System == "ICD10CM") #only ICD diagnosis codes only

str(hep_c_project_HEDIS_value_sets)

hep_c_project_HEDIS_codes <- as.data.frame(unique(hep_c_project_HEDIS_value_sets$Code))
colnames(hep_c_project_HEDIS_codes) <- "Code"

```

```{r}
###  Join patient id table to diagnosis_icd table to bring in first Hep C date
pts_diagnosis <- left_join(patients, diagnosis_icd) #8,479,127 rows
dim(pts_diagnosis)
str(pts_diagnosis)

#identify which observations occurred after First_Date_with_Hep_C_ICD_code
pts_diagnosis$BeforeorAfter <- ifelse(pts_diagnosis$First_Date_with_Hep_C_ICD_code < pts_diagnosis$enc_dt_ds, 0, 
                                      ifelse(pts_diagnosis$First_Date_with_Hep_C_ICD_code == pts_diagnosis$enc_dt_ds, 0, 1))

nrow(pts_diagnosis[(pts_diagnosis$ICD_TYPE == 9),])#7,961,673 rows
nrow(pts_diagnosis[(pts_diagnosis$ICD_TYPE == 10),])#518,101 rows

#remove observations that occurred after Hep C diagnosis
pt_icd_codes <- pts_diagnosis[(pts_diagnosis$BeforeorAfter == 1),]

str(pt_icd_codes)

#Looking unique codes
unique_codes <- sort(unique(pt_icd_codes$icd_dx))
length(unique_codes)
write.csv(unique_codes, "Z:/Value Sets/unique_codes.csv")
```

```{r}
##Join value set and pts_diagnosis code to identify value set name of each icd code
pt_icd_codes_value_sets <- inner_join(hep_c_project_HEDIS_codes, pt_icd_codes, by = c("Code" = "icd_dx"))
dim(pt_icd_codes)
dim(HEDIS_ICD_codes)
dim(pt_icd_codes_value_sets)


##Evaluating join
pt_icd_codes_value_sets[is.na(pt_icd_codes_value_sets$PATIENT_ID) & pt_icd_codes_value_sets$Code_System == "ICD9CM",]
diagnosis_icd[grep("HIV", diagnosis_icd$icd_diagnosis),]

unique_codes_after_join <- as.data.frame(unique(pt_icd_codes_value_sets$Code))

left_join(HEDIS_ICD_codes, unique_codes_after_join)

write.csv(unique_codes_after_join, "Z:/Value Sets/unique_codes_after_join.csv")

#Create table with frequency of icd codes
icd_freq_table <- as.data.frame.matrix(table(pt_icd_codes_value_sets$PATIENT_ID, pt_icd_codes_value_sets$Code))
str(icd_freq_table)

icd_freq_table$PATIENT_ID <- rownames(icd_freq_table)  #Create a column for PATIENT_ID
icd_freq_table <- icd_freq_table[c(57, 1:56)] #move PATIENT_ID column to columns 1
colnames(icd_freq_table)[2:57] <- paste("FREQ", colnames(icd_freq_table[,c(2:57)]), sep = "_")#rename column names to icd_code_freq for columns 2:56
rownames(icd_freq_table) <- NULL#Remove row names from data.frame


#join back with patients id's that were lost; 
all_pts_icd_freq_table <- left_join(patients, icd_freq_table)

# chanage NA's to zeros
all_pts_icd_freq_table[,3:59][is.na(all_pts_icd_freq_table[,3:59])] <- 0
```

```{r}
#subset between HEP C vs Non HEP C and commpare totals

hep_c <- sapply(icd_names, function(x) nrow(subset(all_pts_binned_icd_freq_table, x > 0 & HCV_STATUS == 1)))

nrow(subset(all_pts_binned_icd_freq_table, FREQ_131 > 0 & HCV_STATUS == 1))

non_hep_c <- sapply(icd_names, function(x) nrow(subset(all_pts_binned_icd_freq_table, x > 0 & HCV_STATUS == 0)))

comparison <- ifelse(hep_c_icd_col_sum$Hep_C_percent > non_hep_c_icd_col_sum$Non_Hep_C_percent, 1, 0)

sum(comparison)
```

```{r}
###Create table with 0/1's of icd codes binned by HEDIS value categories; Ever diagnosised? ### 
icd_freq_variable <- names(sexual_activity_codes[2:12000])

for(x in levels(icd_freq_variable))
patients$x <- if(patients$x == 0, 0, 1))#need to find a way to name it

```




```{r}

###  ICD codes binned by CCS categories
###import CCS categories
ccs <- read.csv("Z:/Value Sets/CCSCategoryNames_ICD9.csv", header = TRUE, stringsAsFactor = FALSE)
head(ccs)
str(ccs)

ccs$X.ICD.9.CM.CODE. <- sub(".$", "", ccs$X.ICD.9.CM.CODE.)#remove last character in string
ccs$X.ICD.9.CM.CODE. <- sub("^.", "", ccs$X.ICD.9.CM.CODE.)#remove first character in string
#ccs$X.ICD.9.CM.CODE. <- as.factor(ccs$X.ICD.9.CM.CODE.) #change codes to factor
```

```{r}

###3  Create Frequency Table Binned by CCS groups
subset(ccs, X.ICD.9.CM.CODE. == "7945")

ccs[grep("5920", ccs$X.ICD.9.CM.CODE.),]
pts_diagnosis[grep("5920", pts_diagnosis$icd_dx),]

pts_diagnosis$icd_dx <- gsub("\\.", "", pts_diagnosis$icd_dx)  #remove decimal points

##  join patient icd codes with ccs catgory
###  NOT WORKING - some matches are not happening####
pts_diagnosis_ccs <- left_join(pts_diagnosis, ccs, by = c("icd_dx" = "X.ICD.9.CM.CODE."))
str(pts_diagnosis_ccs)
pts_diagnosis_ccs[is.na(pts_diagnosis_ccs$CCS.CATEGORY),]


#Create table with frequency of icd codes
icd_ccs_freq_table <- as.data.frame.matrix(table(pts_diagnosis_ccs$PATIENT_ID, pts_diagnosis_ccs$CCS.CATEGORY))
str(icd_ccs_freq_table)

icd_ccs_freq_table$PATIENT_ID <- rownames(icd_ccs_freq_table)#Create a column for PATIENT_ID
icd_ccs_freq_table <- icd_ccs_freq_table[c(253, 1:252)]#move PATIENT_ID column to columns 
colnames(icd_ccs_freq_table)[2:252] <- paste("FREQ", colnames(icd_ccs_freq_table[,c(2:252)]), sep = "_")#rename column names to icd_code_freq for columns 2:252
rownames(icd_ccs_freq_table) <- NULL#Remove row names from data.frame


#join back with all patients that were lost; 
all_pts_icd_ccs_freq_table <- left_join(patients, icd_ccs_freq_table)
all_pts_icd_ccs_freq_table[,4:255][is.na(all_pts_icd_ccs_freq_table[,4:255])] <- 0# chanage NA's to zeros


icd_ccs_col_Sums <- colSums(all_pts_icd_ccs_freq_table[4:255],)

as.data.frame(icd_ccs_col_Sums)
sort(icd_ccs_col_Sums)
```

```{r}
###  CPT Tables #######

#reduce tables to only patient_ID and CPT column and join the 3 tables together

reduced_procedure_icd <- procedure_icd[c("PATIENT_ID", "enc_dt_ds", "icd_px", "icd_procedure")]
colnames(reduced_procedure_icd) <- c("PATIENT_ID", "Date", "Code", "Desc")

reduced_cpt <- cpt[c("PATIENT_ID", "enc_dt_ds", "CPT", "CPT_Procedure")]
colnames(reduced_cpt) <- c("PATIENT_ID", "Date", "Code", "Desc")            

reduced_cpt_ucpg <- cpt_ucpg[c("Patient_Id", "Date_of_Service_DS", "CPT_Code")]
colnames(reduced_cpt_ucpg) <- c("PATIENT_ID", "Date", "Code")
reduced_cpt_ucpg$Desc <- NA


all_cpt <- rbind(reduced_procedure_icd, reduced_cpt, reduced_cpt_ucpg)

str(all_cpt)
dim(all_cpt)


###  Join patient id table to all cpt table
pts_cpt <- left_join(patients, all_cpt) 
dim(pts_cpt)
str(pts_cpt)

#identify which observations occurred after First_Date_with_Hep_C_ICD_code
pts_cpt$BeforeorAfter <-ifelse(is.na(pts_cpt$First_Date_with_Hep_C_ICD_code), 1,
                                        ifelse(pts_cpt$First_Date_with_Hep_C_ICD_code < pts_cpt$Date, 0, 1))

#remove observations that occurred after Hep C diagnosis
pts_cpt <- pts_cpt[(pts_cpt$BeforeorAfter == 1),]

nrow(subset(pts_cpt, BeforeorAfter == 1))

#reduce file down to 2 columns - patient_id and icd_dx
pt_cpt_codes <- pts_cpt[c(1,6)]
str(pt_cpt_codes)


##Join value set and pts_cpt code to identify value set name of each icd code
pt_cpt_codes_value_sets <- inner_join(pt_cpt_codes, codes_from_value_sets)
dim(pt_cpt_codes)
dim(codes_from_value_sets)
dim(pt_cpt_codes_value_sets)


#Create table with frequency of icd codes
cpt_freq_table <- as.data.frame.matrix(table(pt_cpt_codes_value_sets$PATIENT_ID, pt_cpt_codes_value_sets$Code))
str(cpt_freq_table)

#Create a column for PATIENT_ID
cpt_freq_table$PATIENT_ID <- rownames(cpt_freq_table) 

#Remove row names from data.frame
rownames(cpt_freq_table) <- NULL

#move PATIENT_ID column to columns 1
cpt_freq_table <- cpt_freq_table[c(107, 1:106)]

#rename column names to icd_code_freq for columns 2:98
colnames(cpt_freq_table)[2:107] <- paste("FREQ", colnames(cpt_freq_table[,c(2:107)]), sep = "_")

#join back with all patients that were lost; 
all_pts_cpt_freq_table <- left_join(patients, cpt_freq_table)

# chanage NA's to zeros
all_pts_cpt_freq_table[,5:110][is.na(all_pts_cpt_freq_table[,5:110])] <- 0


#####CINDY'S CODE ENDS ########
#---------------------------------------
```


```{r}
#Laura's Encounter Variables
encounters_first_hep_c_encounter <- left_join(encounters,patients)
encounters_first_hep_c_encounter$before_diagnosis <- ifelse(encounters_first_hep_c_encounter$Enc_DT_DS < encounters_first_hep_c_encounter$First_Date_with_Hep_C_ICD_code, "TRUE", "FALSE")

#Total_Num_Encounters
patient_ID_encounters <- ddply(encounters_first_hep_c_encounter,.(PATIENT_ID), summarize, Total_Num_Encounters = length(PATIENT_ID[before_diagnosis == "TRUE"]))
patients <- left_join(patients,patient_ID_encounters)

#Total_Num_Outpt_Visits
patient_ID_encounters_outpt <- ddply(encounters_first_hep_c_encounter,.(PATIENT_ID), summarize, Total_Num_Outpt_Visits = length(PATIENT_ID[Enc_EIO %in% c("O", "I, O", "E, O", "E, I, O") & before_diagnosis == "TRUE"]))
patients <- left_join(patients,patient_ID_encounters_outpt)

#Total_Num_Inpt_Admissions
patient_ID_encounters_inpt <- ddply(encounters_first_hep_c_encounter,.(PATIENT_ID), summarize, Total_Num_Inpt_Admissions = length(PATIENT_ID[Enc_EIO %in% c("I", "I, O", "E, I, O", "E, I") & before_diagnosis == "TRUE"]))
patients <- left_join(patients,patient_ID_encounters_inpt)

#Average_LOS
patient_ID_inpt_days <- ddply(encounters_first_hep_c_encounter,.(PATIENT_ID), summarize, Total_Days = sum(LOS_Days[Enc_EIO %in% c("I", "I, O", "E, I, O", "E, I") & before_diagnosis == "TRUE"]))
patients <- left_join(patients,patient_ID_inpt_days)
patients$Average_LOS <- patients$patient_ID_inpt_days/patients$Total_Num_Inpt_Admissions

#Total_Num_ED_Visits
patient_ID_encounters_ED <- ddply(encounters_first_hep_c_encounter,.(PATIENT_ID), summarize, Total_Num_ED_Visits = length(PATIENT_ID[Enc_EIO %in% c("E, I", "E", "E, I, O", "E, O") & before_diagnosis == "TRUE"]))
patients <- left_join(patients,patient_ID_encounters_ED)
unique(encounters$Enc_EIO)

#Num_Specialty_Docs


#Insurance_Status_History
patient_ID_insurancecount <- ddply(encounters_first_hep_c_encounter,.(PATIENT_ID), summarize, InsuranceCount = length(PATIENT_ID[!is.na(Fin_Class) & before_diagnosis == "TRUE"]))

```

```{r}
#Laura's Encounter Variables
encounters_first_hep_c_encounter <- left_join(encounters,patients)
encounters_first_hep_c_encounter$before_diagnosis <- ifelse(encounters_first_hep_c_encounter$Enc_DT_DS < encounters_first_hep_c_encounter$First_Date_with_Hep_C_ICD_code, "TRUE", "FALSE")

#Total_Num_Encounters
patient_ID_encounters <- ddply(encounters_first_hep_c_encounter,.(PATIENT_ID), summarize, Total_Num_Encounters = length(PATIENT_ID[before_diagnosis == "TRUE"]))
patients <- left_join(patients,patient_ID_encounters)

#Total_Num_Outpt_Visits
patient_ID_encounters_outpt <- ddply(encounters_first_hep_c_encounter,.(PATIENT_ID), summarize, Total_Num_Outpt_Visits = length(PATIENT_ID[Enc_EIO %in% c("O", "I, O", "E, O", "E, I, O") & before_diagnosis == "TRUE"]))
patients <- left_join(patients,patient_ID_encounters_outpt)

#Total_Num_Inpt_Admissions
patient_ID_encounters_inpt <- ddply(encounters_first_hep_c_encounter,.(PATIENT_ID), summarize, Total_Num_Inpt_Admissions = length(PATIENT_ID[Enc_EIO %in% c("I", "I, O", "E, I, O", "E, I") & before_diagnosis == "TRUE"]))
patients <- left_join(patients,patient_ID_encounters_inpt)

#Average_LOS
patient_ID_inpt_days <- ddply(encounters_first_hep_c_encounter,.(PATIENT_ID), summarize, Total_Days = sum(LOS_Days[Enc_EIO %in% c("I", "I, O", "E, I, O", "E, I") & before_diagnosis == "TRUE"]))
patients <- left_join(patients,patient_ID_inpt_days)
patients$Average_LOS <- patients$patient_ID_inpt_days/patients$Total_Num_Inpt_Admissions

#Total_Num_ED_Visits
patient_ID_encounters_ED <- ddply(encounters_first_hep_c_encounter,.(PATIENT_ID), summarize, Total_Num_ED_Visits = length(PATIENT_ID[Enc_EIO %in% c("E, I", "E", "E, I, O", "E, O") & before_diagnosis == "TRUE"]))
patients <- left_join(patients,patient_ID_encounters_ED)
unique(encounters$Enc_EIO)

#Insurance_Aided

levels(encounters_first_hep_c_encounter$Fin_Class) <- c("Insured", "Insured", "Aided", "Aided", 
                                     "Insured", "Insured", "Aided", "Insured", 
                                     "Insured", "Insured", "Insured", "Insured", 
                                     "Insured", "Aided", "Aided", "Aided", 
                                     "Aided", "Insured", "Insured", "Insured",
                                     "Insured", "Insured", "Self Pay", "Self Pay")


patient_ID_insurance_aided <- ddply(encounters_first_hep_c_encounter,.(PATIENT_ID), summarize, InsuranceAidedCt = length(PATIENT_ID[Fin_Class == "Aided" & before_diagnosis == "TRUE"]))
patient_ID_insurance_aided$Insurance_Aided <- ifelse(patient_ID_insurance_aided$InsuranceAidedCt>0,"TRUE", "FALSE")
patients <- left_join(patients, patient_ID_insurance_aided[,3])


#Insurance_Gap
patient_ID_insurancegap <- ddply(encounters_first_hep_c_encounter,.(PATIENT_ID), summarize, InsuranceGap = length(PATIENT_ID[(is.na(Fin_Class) | Fin_Class == "Self Pay") & before_diagnosis == "TRUE"]))
patient_ID_insurancecount$Insurance_Gap <- ifelse(patient_ID_insurancegap$InsuranceGap>0,"TRUE", "FALSE")
patients <- left_join(patients, patient_ID_insurancegap[,3])

#Zip_Code
encounters_minus_zip <- encounters_first_hep_c_encounter[!is.na(encounters_first_hep_c_encounter$Zip_Code_DID),]

patient_ID_zip <- encounters_minus_zip %>% 
  group_by(PATIENT_ID) %>% 
  summarise(c = names(table(Zip_Code_DID))[which.max(table(Zip_Code_DID))])

patients <- left_join(patients, patient_ID_zip)
patients <- left_join(patients, ACS)

```
